trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- bash: |
    RANDOM_NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 13 ; echo '')
    echo "##vso[task.setvariable variable=clusterName;]$RANDOM_NAME"
  displayName: Generating random cluster name
- task: AzureCLI@2
  displayName: 'Creating AKS cluster with App Gateway'
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship(d09f4363-eae7-4c79-864e-08154540c083)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './create-appg-aks.sh'
    arguments: '$(clusterName)'
- bash: |
    wget https://github.com/rancher/cli/releases/download/v2.4.10/rancher-linux-amd64-v2.4.10.tar.gz
    tar -zxvf rancher-linux-amd64-v2.4.10.tar.gz

    sudo chmod +x ./rancher-v2.4.10/rancher && sudo mv ./rancher-v2.4.10/rancher /usr/local/bin
  displayName: Install Rancher CLI

- bash: rancher login https://nonprod.rancher.azure.boxboat.io --token $RANCHER_TOKEN --context "$RANCHER_CONTEXT"
  displayName: Rancher Login
  env:
    RANCHER_TOKEN: $(RancherToken)
    RANCHER_CONTEXT: $(RancherLocalSystemContext)

- bash: |
    AKS_CLUSTER_NAME="azaks-$(clusterName)-sbx"
    rancher clusters create $AKS_CLUSTER_NAME --import
    APPLY_CMD=$(rancher clusters import $AKS_CLUSTER_NAME -q | head -1)

    eval $APPLY_CMD
  displayName: Rancher import


