trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- task: AzureCLI@2
  displayName: 'Creating AKS cluster with App Gateway'
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship(d09f4363-eae7-4c79-864e-08154540c083)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './create-appg-aks.sh'
    arguments: '$(clusterName)'
- bash: |
    wget https://github.com/rancher/cli/releases/download/v2.4.10/rancher-linux-amd64-v2.4.10.tar.gz
    tar -zxvf rancher-linux-amd64-v2.4.10.tar.gz

    sudo chmod +x ./rancher-v2.4.10/rancher && sudo mv ./rancher-v2.4.10/rancher /usr/local/bin
  displayName: Install Rancher CLI

- bash: rancher login https://nonprod.rancher.azure.boxboat.io --token $RANCHER_TOKEN
  displayName: Rancher Login
  env:
    RANCHER_TOKEN: $(RancherToken)

- bash: rancher clusters import azaks-$(clusterName)-sbx
  displayName: Rancher import


